apiVersion: apps/v1
kind: Deployment
metadata:
  name: xyz-api-deployment
  labels:
    app: xyz-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xyz-api
  template:
    metadata:
      labels:
        app: xyz-api
    spec:
      containers:
      - name: xyz-api-container
        image: ghcr.io/eparkertamu96/xyz:latest  # Replace with your Python API Docker image
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: xyz-api-service
spec:
  selector:
    app: xyz-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
