name: EKS Blueprint Infrastructure

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCOUNT_NUMBER: ${{ secrets.AWS_ACCOUNT_NUMBER }}
  
jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.3
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt install make nodejs
        sudo npm install -g n
        n stable
        sudo npm install -g aws-cdk
        sudo npm install
        
    - name: Bootstrap Environment
      run: cdk bootstrap aws://$AWS_ACCOUNT_NUMBER/$AWS_REGION
      
    - name: Deploy Infrastructure
      run: cdk deploy --require-approval never
      
   
        
  
